### ISSUE TITLE
The shape of embed_token layer error

### ISSUE THREAD

**Issue by cocoshe** [TencentARC/SmartEdit#10]
The shape of `embed_token` layer (the first layer of the model) just different between the llava-v1 and the SmartEdit.
```python
(Pdb) LLM_ckpt_new['base_model.model.embed_tokens.weight'].shape   # llava-v1-13B (after merging llama-v1 and the corresponding delta weight)
torch.Size([32003, 5120])
(Pdb) self.model.base_model.model.embed_tokens  # SmartEdit
Embedding(32035, 5120)
```
I check the origional Llama weight, and the shape is `[32000, *]`
I tried 7B, and the `embed_tokens` layer of llava is merge from delta weight, and the layer shape in delta weight is always `32003` for both 7B and 13B. None of these fit with each other.

**Comment by yuzhou914** [comment]
Hi, we have updated the explanation and how to solve, please take a look.
<img width="649" alt="企业微信截图_1714292031288" src="https://github.com/TencentARC/SmartEdit/assets/56435130/9e94fced-ed90-431b-a967-cb3707f084de">

**Comment by cocoshe** [comment]
OK, thanks for your reply.
