### ISSUE TITLE
ImportError: cannot import name 'PeftConfig' from 'peft.utils'

### ISSUE THREAD

**Issue by terry2100** [TencentARC/SmartEdit#13]
SmartEdit/test/DS_PeftForLoRA.py", line 50, in <module>
    from peft.utils import (
ImportError: cannot import name 'PeftConfig' from 'peft.utils'

Hi, can you share your peft version?

**Comment by huangjf11** [comment]
+1，我也遇到了这个问题

**Comment by yuzhou914** [comment]
Hi, we use peft==0.4.0 in SmartEdit.
