### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'SmartEdit-7B/adapter_config.json' 

### ISSUE THREAD

**Issue by huangjf11** [TencentARC/SmartEdit#14]
Hello, there was an error message during inference indicating that 'SmartEdit-7B/adapter_config.json' does not exist. 

The officially released SmartEdit-7B and 13B models do not include 'adapter_config.json'. 

Could you help me solve this issue?

![image](https://github.com/TencentARC/SmartEdit/assets/43243253/ab0bd16f-7a60-4b87-986c-09698c4deefa)

**Comment by yuzhou914** [comment]
Hi, the "adapter_config.json" is in LLM-15000 file.
