### ISSUE TITLE
When will you release the code and checkpoint?

### ISSUE THREAD

**Issue by wrt2000** [TencentARC/SmartEdit#2]
I am highly interested in your work and can't wait to try it. When will the full code and checkpoints be released?

**Comment by yuzhou914** [comment]
Thanks for your interest. We are still preparing the code and release after the CVPR released result.

**Comment by khushalrs** [comment]
Yes me too, I also want to try the model and leverage its capabilities. By when are you releasing the checkpoints and training modules?

**Comment by yuzhou914** [comment]
We definitely promise to release code and checkpoints. However, we still have to prepare for the potential article publication, which might delay the code release because of further refinement. Hopefully, we will release the code in March.

**Comment by NuanBaobao** [comment]
Is it possible to publish the code and weights file now that it's April?

**Comment by LiangbinXie** [comment]
Hello, we have released our code. Thanks for your patience!
