### ISSUE TITLE
Question about finetune my own instruction-based editing dataset

### ISSUE THREAD

**Issue by Cominclip** [TencentARC/SmartEdit#20]
Hi, thank you for your great work!
I want to finetune the pre-trained SmartEdit-7b on my own instruction-based editing dataset. As I understand it, I only need to train stage-2, but according to your code, the second stage training consists of two parts: MLLMSD_7b and SmartEdit_7b. What is the focus of these two parts? Do I need to train both of them or just the SmartEdit_7b part?

**Comment by yuzhou914** [comment]
Thank you for your interest in our work. In stage-2, the first part is to train the MLLM with SD without BIM module, the second part involves BIM module with zero-init module in the beginning. If you want to use the whole part of SmartEdit, please train both of them.
