### ISSUE TITLE
inference issue

### ISSUE THREAD

**Issue by shuyansy** [TencentARC/SmartEdit#23]
Thanks so much for the excellent work! Hoever I met some issues in inference. Since the LLaVA-1.1 can not be founded, I replace it with LLAVA-1.5, but it occur the following issue. Could you provide the weight? Thanks again for your time!
![截屏2024-08-08 下午5 14 44](https://github.com/user-attachments/assets/89ae13cc-d2ab-40aa-89ae-feb734e30f0e)

**Comment by yuzhou914** [comment]
Please do not use LLaVA-1.5 and use LLaVA-1.1, which can be found in official LLaVA github web.
