### ISSUE TITLE
llava-1.1官方网站好像下架了

### ISSUE THREAD

**Issue by learn01one** [TencentARC/SmartEdit#26]
你好，llava-1.1官方网站好像下架了，可以直接使用llava-1.5？

**Comment by whu125** [comment]
所以能用吗？求教

**Comment by learn01one** [comment]
后续没关注了哈



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年12月5日(周四) 上午10:29
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [TencentARC/SmartEdit] llava-1.1官方网站好像下架了 (Issue #26)




 
所以能用吗？求教

**Comment by baihuple** [comment]
可以用了吗？我用 LLaVa-7B-1.5 替代，tensor 报错，32000 and 31997
