### ISSUE TITLE
Questions about  load_pretrained_LLaMA_for_inference 

### ISSUE THREAD

**Issue by qxhhou** [TencentARC/SmartEdit#6]
In model.DS_SmartEdit_model  line:307

` # inference 1.with pretrained LLaMA+LoRA
    def load_pretrained_LLaMA_for_inference(self, pretrained_LLaMA):
        LLaMA_weights = torch.load(pretrained_LLaMA, map_location="cpu")
        # 1.
        LLM_ckpt_new = {}
        for k, v in LLaMA_weights.items():
            if 'model.base_model.model.' in k:
                LLM_ckpt_new[k[len('model.'):]] = v
                # remove 'model.'
        # LLM_ckpt_new['base_model.model.embed_tokens.weight']
        self.model.load_state_dict(LLM_ckpt_new, strict=True)`

 pretrained_LLaMA="./checkpoints/SmartEdit-7B/LLM-15000/adapter_model.bin" , it only saves LoRA weights
 It seems that  "strict="True""  is not proper here

**Comment by yuzhou914** [comment]
Sorry for my negligence since when I upload the checkpoint, I only upload lora weight. While you need to merge the LLaVA-LLM weight with lora first and load model.

**Comment by xmu-xiaoma666** [comment]
> Sorry for my negligence since when I upload the checkpoint, I only upload lora weight. While you need to merge the LLaVA-LLM weight with lora first and load model.

How to merge the LLaVA-LLM weight with lora? Can you provide the code that can run normally？
