### ISSUE TITLE
Training Cost

### ISSUE THREAD

**Issue by lzw-lzw** [TencentARC/SmartEdit#7]
Great work! May I ask how many GPUs were used during the training process and how long did it take? Thank you!

**Comment by yuzhou914** [comment]
Thanks for your interest. All training processes are done by 8 GPUs, SmartEdit-7B by 8xA100, SmartEdit-13B by 8xH800. Since there are two stages for training, the total training process may depend 2~3 days.

**Comment by realmoment2017** [comment]
I wonder if it is possible to list more details of the training cost for each stage? I find the first stage only takes around 60 hrs with 8xA100. Just want to check with you to see if there is anything not correctly aligned. Thank you.
