### ISSUE TITLE
Testing Question

### ISSUE THREAD

**Issue by LL3RD** [TencentARC/SmartEdit#8]
Thanks for your code and i have some problem when testing the smartedit model.

When using the llava-7b model (merged the original llama-7b model and the[delta weight]((https://huggingface.co/liuhaotian/LLaVA-Lightning-7B-delta-v1-1))), the language model output the following sentence:

ASSISTANT: <img_3> <img_1> <img_3> <img_14> <img_14> <img_3> <img_3> <img_14> <img_14> <img_14> <img_14> <img_14> <img_14> <img_14> <img_14> <img_14> <img_14> <img_14> <img_14> <img_14> <img_14> <img_14> <img_14> <img_5> <img_5> <img_5> <img_5> <img_14> <img_5> <img_5> <img_5> <img_5> <img_5> <img_5> <img_5> <img_5>

which seems wrong and results in a bad image output. Do you have any ideas about this problem?

**Comment by yuzhou914** [comment]
The result is abnormal. This is because your llava checkpoint preparation is wrong. Please carefully follow the instruction to prepare llava checkpoint, the delta weight needs to be converted first. I suggest that you could test the conversation by llava first to verify that if your llava checkpoint preparation is correct (the conversation by llava is correct). Then test the smartedit.

![企业微信截图_1714090009391](https://github.com/TencentARC/SmartEdit/assets/56435130/bb7c0987-2a40-4dfa-9190-506df625a4d9)

**Comment by terry2100** [comment]
is base model of llava1.1   llama-7b? or llama-2-7b or others?

**Comment by yuzhou914** [comment]
base model is llava-1.1

**Comment by terry2100** [comment]
Thanks for reply! yes I have merged the llava 1.1 model and when I run test.py I got this error:
RuntimeError: Error(s) in loading state_dict for LlamaModel:
        Missing key(s) in state_dict: "layers.32.self_attn.q_proj.weight", "layers.32.self_attn.k_proj.weight", "layers.32.self_attn.v_proj.weight", "layers.32.self_attn.o_proj.weight", "layers.32.self_attn.rotary_emb.inv_freq", "layers.32.mlp.gate_proj.weight", "layers.32.mlp.down_proj.weight", "layers.32.mlp.up_proj.weight", "layers.32.input_layernorm.weight", "layers.32.post_attention_layernorm.weight", "layers.33.self_attn.q_proj.weight", "layers.33.self_attn.k_proj.weight", "layers.33.self_attn.v_proj.weight", "layers.33.self_attn.o_proj.weight", "layers.33.self_attn.rotary_emb.inv_freq", "layers.33.mlp.gate_proj.weight", "layers.33.mlp.down_proj.weight", "layers.33.mlp.up_proj.weight", "layers.33.input_layernorm.weight", "layers.33.post_attention_layernorm.weight", "layers.34.self_attn.q_proj.weight", "layers.34.self_attn.k_proj.weight", "layers.34.self_attn.v_proj.weight", "layers.34.self_attn.o_proj.weight", "layers.34.self_attn.rotary_emb.inv_freq", "layers.34.mlp.gate_proj.weight", "layers.34.mlp.down_proj.weight", "layers.34.mlp.up_proj.weight", "layers.34.input_layernorm.weight", "layers.34.post_attention_layernorm.weight", "layers.35.self_attn.q_proj.weight", "layers.35.self_attn.k_proj.weight", "layers.35.self_attn.v_proj.weight", "layers.35.self_attn.o_proj.weight", "layers.35.self_attn.rotary_emb.inv_freq", "layers.35.mlp.gate_proj.weight", "layers.35.mlp.down_proj.weight", "layers.35.mlp.up_proj.weight", "layers.35.input_layernorm.weight", "layers.35.post_attention_layernorm.weight", "layers.36.self_attn.q_proj.weight", "layers.36.self_attn.k_proj.weight", "layers.36.self_attn.v_proj.weight", "layers.36.self_attn.o_proj.weight", "layers.36.self_attn.rotary_emb.inv_freq", "layers.36.mlp.gate_proj.weight", "layers.36.mlp.down_proj.weight", "layers.36.mlp.up_proj.weight", "layers.36.input_layernorm.weight", "layers.36.post_attention_layernorm.weight", "layers.37.self_attn.q_proj.weight", "layers.37.self_attn.k_proj.weight", "layers.37.self_attn.v_proj.weight", "layers.37.self_attn.o_proj.weight", "layers.37.self_attn.rotary_emb.inv_freq", "layers.37.mlp.gate_proj.weight", "layers.37.mlp.down_proj.weight", "layers.37.mlp.up_proj.weight", "layers.37.input_layernorm.weight", "layers.37.post_attention_layernorm.weight", "layers.38.self_attn.q_proj.weight", "layers.38.self_attn.k_proj.weight", "layers.38.self_attn.v_proj.weight", "layers.38.self_attn.o_proj.weight", "layers.38.self_attn.rotary_emb.inv_freq", "layers.38.mlp.gate_proj.weight", "layers.38.mlp.down_proj.weight", "layers.38.mlp.up_proj.weight", "layers.38.input_layernorm.weight", "layers.38.post_attention_layernorm.weight", "layers.39.self_attn.q_proj.weight", "layers.39.self_attn.k_proj.weight", "layers.39.self_attn.v_proj.weight", "layers.39.self_attn.o_proj.weight", "layers.39.self_attn.rotary_emb.inv_freq", "layers.39.mlp.gate_proj.weight", "layers.39.mlp.down_proj.weight", "layers.39.mlp.up_proj.weight", "layers.39.input_layernorm.weight", "layers.39.post_attention_layernorm.weight". 
        size mismatch for embed_tokens.weight: copying a param with shape torch.Size([32000, 4096]) from checkpoint, the shape in current model is torch.Size([32000, 5120])

my script is 
python test/DS_SmartEdit_test.py --is_understanding_scenes True --model_name_or_path checkpoints/vicuna-13b-v1.1 --LLaVA_model_path checkpoints/llava-7b-v1-1 --save_dir test_result --steps 15000 --total_dir checkpoints/TencentARC/SmartEdit-7B --sd_qformer_version "v1.1-7b" --resize_resolution 256

**Comment by yuzhou914** [comment]
Hi, maybe because you use vicuna-13b that causes the problem, please re-check.

**Comment by terry2100** [comment]
many Thanks!
